server:
  port: 9008
spring:
  application:
    name: tensquare-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_user?characterEncoding=utf-8&useSSL=true
    username: root
    password: mysql
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: localhost
  rabbitmq:
    host: localhost